### ISSUE TITLE
Stage 1: House Pool Calculations and Logic

### ISSUE THREAD

**Issue by nuCodeIO** [Luna-Fi/lunafi-smart-contracts#23]
Refer to the spreadsheet. The House Pool contracts need to be updated with logic to carry out calculations for different operations:

- [ ] Maintain key values for each house pool https://github.com/Luna-Fi/lunafi-smart-contracts/issues/25
- [ ] Deposits to pool https://github.com/Luna-Fi/lunafi-smart-contracts/issues/26
- [ ] New bets being added
- [ ] EV value updates
- [ ] Bet outcomes both winning and loosing
- [ ] Withdrawal checks: https://github.com/Luna-Fi/lunafi-smart-contracts/issues/27
- [ ] Withdrawals after checks: https://github.com/Luna-Fi/lunafi-smart-contracts/issues/27

Google Spreadsheet with House Pool Calculations: https://docs.google.com/spreadsheets/d/15VDcer5LOj6sc4AGocO-indm0sJryE9yumquNJUvf8A/edit#gid=0
