### ISSUE TITLE
Stage 2: House Pool Contracts

### ISSUE THREAD

**Issue by nuCodeIO** [Luna-Fi/lunafi-smart-contracts#28]
Stage 2: Enhancing House Pool Contracts with all calculations except (1) Orders and Bettings data (2) Meta Transactions

Google Spreadsheet with House Pool Calculations: https://docs.google.com/spreadsheets/d/15VDcer5LOj6sc4AGocO-indm0sJryE9yumquNJUvf8A/edit#gid=0

- [ ] Maintain key values for each house pool: https://github.com/Luna-Fi/lunafi-smart-contracts/issues/25
- [ ] Oracle mechanism for ME and EV: covered in https://github.com/Luna-Fi/lunafi-smart-contracts/issues/25
- [ ] Track current price of LP: covered in https://github.com/Luna-Fi/lunafi-smart-contracts/issues/25
- [ ] User specific data: https://github.com/Luna-Fi/lunafi-smart-contracts/issues/29
